// AUTO-GENERATED from the fresh-install SQL seed scripts.
// Do not edit this file by hand. Regenerate from the seed package instead.

import appData from './app-data.json';

export type StaticTableName = keyof typeof appData.tables;
export const APP_DATA = appData.tables;
export const APP_DATA_META = appData.meta;

export function getStaticTable<T extends StaticTableName>(name: T): (typeof APP_DATA)[T] {
  return APP_DATA[name];
}

export default APP_DATA;
